spring:
  profiles:
    active: prod
---
  
server:
 port: 8091
 servlet:
  context-path: /
  
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  profiles: prod
  
  
#mybatis:
#  type-aliases-package: com.example.demo.pojo
#  mapper-locations: classpath:/mybatis/mappers/*.xml
#  #开启驼峰映射
#  configuration:
#    map-underscore-to-camel-case: true
    
mybatis-plus:
 type-aliases-package: com.example.demo.pojo  
 mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
 configuration:
    map-underscore-to-camel-case: true


---
server:
  port: 8009
  servlet:
    context-path: /
    
user: 
  id: 150
  username: 春节快乐
  age: 18556
  
spring:
  profiles: dev














